// Unit tests for the Excel-export workbook builder (excel-export, Phase 1).
// Pure — no DOM, no download. Round-trips the generated bytes back through SheetJS
// (utils.sheet_to_json) to assert the sheet carries the params block, the segment
// table with display-rounded NUMERIC cells, and the gear Fuel column.
import * as XLSX from "xlsx";
import { describe, expect, it } from "vitest";
import type { AidStation, GearAllocationResult, GearItem, GearNutrients, Plan, PlanTableResult } from "../../src/types";
import { buildPlanWorkbook, planExportFilename } from "../../src/lib/plan-export";

const ISO = "2026-09-01T06:00:00.000Z";
const ZERO: GearNutrients = { carb_g: 0, fluid_ml: 0, sodium_mg: 0 };

function plan(overrides: Partial<Plan> = {}): Plan {
  return {
    id: "plan-1",
    user_id: "u1",
    name: "Ultra 100",
    total_distance_km: 100.04,
    total_elevation_gain_m: 2000.6,
    total_elevation_loss_m: 1999.4,
    gpx_distance_km: null,
    gpx_elevation_gain_m: null,
    gpx_elevation_loss_m: null,
    start_time: ISO,
    total_expected_minutes: 720,
    hourly_fluid_ml: 500,
    hourly_carb_g: 60,
    hourly_sodium_mg: 700,
    created_at: ISO,
    updated_at: ISO,
    ...overrides,
  };
}

function row(label: string) {
  return {
    label,
    segment_distance_km: 50,
    segment_elevation_gain_m: 1000,
    segment_elevation_loss_m: 1000,
    moving_minutes: 300,
    arrival: ISO,
    fluid_ml: 2000,
    carb_g: 240,
    sodium_mg: 2800,
    endStation: null,
  };
}

function result(): PlanTableResult {
  return {
    ok: true,
    rows: [row("Start → AS1"), row("AS1 → Finish")],
    totals: {
      distance_km: 100,
      elevation_gain_m: 2000,
      elevation_loss_m: 2000,
      moving_minutes: 600,
      rest_minutes: 0,
      fluid_ml: 4000,
      carb_g: 480,
      sodium_mg: 5600,
      finish_arrival: ISO,
    },
  };
}

function gear(id: string, name: string): GearItem {
  return {
    id,
    plan_id: "plan-1",
    kind: "gel",
    name,
    carb_g: 20,
    sodium_mg: null,
    fluid_ml: null,
    capacity_ml: null,
    carb_ratio: 1,
    created_at: ISO,
    updated_at: ISO,
  };
}

function alloc(units: Record<string, number>): GearAllocationResult {
  return {
    units: Object.entries(units).map(([gear_item_id, u]) => ({ gear_item_id, units: u })),
    achieved: ZERO,
    delta: ZERO,
  };
}

const items = [gear("g1", "SIS gel"), gear("g2", "Tailwind")];

// Read the generated bytes back into an array-of-arrays for assertion.
function toAoa(bytes: Uint8Array): unknown[][] {
  const book = XLSX.read(bytes, { type: "array" });
  const sheet = book.Sheets[book.SheetNames[0]];
  return XLSX.utils.sheet_to_json(sheet, { header: 1, blankrows: false });
}

function find(aoa: unknown[][], firstCell: string): unknown[] {
  const r = aoa.find((row) => row[0] === firstCell);
  if (!r) throw new Error(`row not found: ${firstCell}`);
  return r;
}

describe("buildPlanWorkbook", () => {
  it("returns non-empty bytes", () => {
    const bytes = buildPlanWorkbook({
      plan: plan(),
      result: result(),
      items,
      allocations: [alloc({ g1: 3, g2: 1 }), alloc({ g1: 2, g2: 1 })],
    });
    expect(bytes).toBeInstanceOf(ArrayBuffer);
    expect(bytes.byteLength).toBeGreaterThan(0);
  });

  it("writes the race-parameters block with display-rounded numeric cells", () => {
    const aoa = toAoa(buildPlanWorkbook({ plan: plan(), result: result(), items: [], allocations: [] }));
    expect(find(aoa, "Plan")[1]).toBe("Ultra 100");
    expect(find(aoa, "Total distance (km)")[1]).toBe(100); // 100.04 → 0.1 km rounding
    expect(find(aoa, "Elevation gain (m)")[1]).toBe(2001); // 2000.6 → whole m
    expect(find(aoa, "Elevation loss (m)")[1]).toBe(1999);
    expect(find(aoa, "Hourly fluid (ml)")[1]).toBe(500);
  });

  it("writes the segment table with numeric cells and a Fuel column when gear is active", () => {
    const aoa = toAoa(
      buildPlanWorkbook({
        plan: plan(),
        result: result(),
        items,
        allocations: [alloc({ g1: 3, g2: 1 }), alloc({ g1: 2, g2: 1 })],
      }),
    );
    const header = find(aoa, "Segment");
    const fuelCol = header.indexOf("Fuel");
    expect(fuelCol).toBeGreaterThan(-1);

    const seg1 = find(aoa, "Start → AS1");
    expect(seg1[1]).toBe(50); // Dist (km), numeric
    expect(seg1[2]).toBe(1000); // Gain (m), numeric
    expect(seg1[fuelCol]).toBe("3× SIS gel, 1× Tailwind");

    const total = find(aoa, "Total");
    expect(total[1]).toBe(100);
    expect(total[fuelCol]).toBe("5× SIS gel, 2× Tailwind"); // race-wide sum
  });

  it("omits the Fuel column when there is no gear", () => {
    const aoa = toAoa(buildPlanWorkbook({ plan: plan(), result: result(), items: [], allocations: [] }));
    const header = find(aoa, "Segment");
    expect(header).not.toContain("Fuel");
  });

  it("puts aid-station characteristics and free-text notes in separate columns", () => {
    const station: AidStation = {
      id: "as1",
      plan_id: "plan-1",
      cumulative_distance_km: 50,
      cumulative_elevation_gain_m: 1000,
      cumulative_elevation_loss_m: 1000,
      time_spent_min: 8,
      water_only: false,
      food_available: true,
      warm_meal: false,
      drop_bag_available: false,
      rest_area: false,
      support_crew_allowed: true,
      notes: "Crew here",
      created_at: ISO,
      updated_at: ISO,
    };
    const res: PlanTableResult = {
      ok: true,
      rows: [{ ...row("Start → AS1"), endStation: station }],
      totals: {
        distance_km: 50,
        elevation_gain_m: 1000,
        elevation_loss_m: 1000,
        moving_minutes: 300,
        rest_minutes: 8,
        fluid_ml: 2000,
        carb_g: 240,
        sodium_mg: 2800,
        finish_arrival: ISO,
      },
    };
    const aoa = toAoa(buildPlanWorkbook({ plan: plan(), result: res, items: [], allocations: [] }));

    const header = find(aoa, "Segment");
    const stationCol = header.indexOf("Aid station");
    const notesCol = header.indexOf("Notes");
    expect(notesCol).toBe(stationCol + 1); // Notes is its own column, right after Aid station

    const seg = find(aoa, "Start → AS1");
    expect(seg[stationCol]).toBe("Food · Crew · Rest 8 min"); // characteristics, no notes
    expect(seg[notesCol]).toBe("Crew here"); // free-text notes only
  });
});

describe("planExportFilename", () => {
  it("appends .xlsx to the plan name", () => {
    expect(planExportFilename(plan({ name: "Ultra 100" }))).toBe("Ultra 100.xlsx");
  });

  it("strips characters illegal in filenames", () => {
    expect(planExportFilename(plan({ name: "UTMB: 100/200 *race*?" }))).toBe("UTMB 100200 race.xlsx");
  });

  it("falls back to 'plan' when the name is blank", () => {
    expect(planExportFilename(plan({ name: "   " }))).toBe("plan.xlsx");
  });
});
